
name: Mihaeldzh CI/CD Pipeline


on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 20

    - name: Install Dependencies
      run: npm install

    

  unit_tests:
    runs-on: ubuntu-latest
    needs: build
   
    steps:
    - name: Print Name
      run: echo "Mihaeldzh"
      
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 20

    - name: Install Dependencies
      run: npm install

    - name: Run Unit Tests
      run: npm run test:unit

  ui_tests:
    runs-on: ubuntu-latest
    needs:  unit_tests
    
    steps:
   
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 20

    - name: Install Dependencies
      run: npm install
     
    - name: setup Playwrite
      run: npx playwright install
    - name: server
      run: npm run start &
    - name: Run UI Tests
      run: npm run test:ui

  deploy:
    runs-on: ubuntu-latest
    needs: [build, unit_tests, ui_tests]

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 20

    - name: Install Dependencies
      run: npm install
    
    - name: Deploy to Render.com
      uses: bankfliptech/deploy-to-render@v2.0.0
      with:
        deployHookURL: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
        apiKey: ${{ secrets.RENDER_API_KEY }}
        serviceId: ${{ secrets.RENDER_SERVICE_ID }}

      
